class MessageConstants:
    WATCH_ON_TWITCH = "Only one stream was selected. Would you like to watch on Twitch instead of your selected site?"
    NO_SITE_SELECTED = "No website selected."
    NO_STREAMS_SELECTED = "No streams selected."
    INVALID_TEAM_NAME = "Team names must be 20 characters or less, and may only contain letters, numbers, and spaces."
    RESERVED_NAME = "Team name is reserved by StreamOpener and cannot be used."
    DUPLICATE_TEAM = "Team name is already in use."
    ALNUM_ONLY = "Team name may only contain letters, numbers, and spaces."
    TEAM_NAME_LENGTH = "Team name must be between 1-20 characters."
    ALL_SPACES = "Team name cannot be all spaces."
    FILTER_ADDED = "Filter added: {0}"
    FILTER_ALREADY_EXISTS = "Filter already exists."
    NO_FILTER_INFO_PROVIDED = "At least one field is required to create a filter."
    INVALID_GAME = "Game not recognized by Twitch. Please enter the game name exactly as it appears on Twitch."
    ACCESS_TOKEN = "Please enter the access_token from the URL you were redirected to."